### PR TITLE
Cleanup repo

### PR DESCRIPTION
**Pull request by rlouf**
Moved a ton of stuff around.

- [ ] Changer l'adresse du fichier contenant les sondages de popularite dans le notebook du modèle correspondant
- [ ] Changer le chemin vers ce même fichier dans le script qui crée le badge en CI

Good to review in the meantime (will be easier if you just click on the branch name above to see the repo structure)

### CODE REVIEW

**Review by AlexAndorra — CHANGES_REQUESTED** [review]
Thanks @rlouf, that looks good!
Just a couple things:
- `paris_city_council_2008.xlsx` and `paris_city_council_2014.xlsx` should be in `/sondages`, not in `/classement-instituts` because these are raw polls, not results of the pollster ratings script
- `results_by_regions.csv`, `results_by_districts_paris.xlsx` and `results_by_departments.xlsx` are not raw, but the result of running `format_generic_results.ipynb` on the raw results files. As they are meant to be replaced by the `json` files, you can keep them here though -- I'll let you choose what you prefer here
- In `sondages`, what's the difference between `presidentielles.json` and `presidentielles_2017.json`?

**Comment by rlouf** [comment]
>     * In `sondages`, what's the difference between `presidentielles.json` and `presidentielles_2017.json`?

538 divides its poll data between e.g. for presidential elections `presidential.csv` and `presidential_historical.csv` which contains all the elections but the previous one. These files can get pretty big quickly, and `presidentielles.json` will be needed more frequently than the others hence the separation. Does it make sense?

**Comment by AlexAndorra** [comment]
So `presidentielles.json` is all elections except 2017, and `presidentielles_2017.json` is only 2017?

**Comment by rlouf** [comment]
I see. Either we do it by year and append `2022` to the first one, or replace `2017` with `historical`. I think I prefer the first option, much clearer what's available.

**Comment by AlexAndorra** [comment]
Ha ha ha, go sleep man!

>  I think I prefer the first option, it makes it more obvious what's available.

I don't have any strong preference, so I'll let you choose. I'd say my only requirement is indeed that what's available is clear and explicit

**Comment by rlouf** [comment]
> I'd say my only requirement is indeed that what's available is clear and explicit

Yeah, like `tour1_complet_unitedfl.csv` ? :stuck_out_tongue:

**Comment by AlexAndorra** [comment]
> Yeah, like tour1_complet_unitedfl.csv ? 😛

_Exactly_! You Sir read me like an open book

**Comment by rlouf** [comment]
Is it to your liking now sir?

**Review by AlexAndorra — APPROVED** [review]
Yes, this is all looking good now my minion!

**Pull request merged**
